name: act_draw_explain
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

# `flutter pub outdated` to see what can be upgraded
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  sprintf: ^6.0.0
  auto_size_text: ^3.0.0
  pref: ^2.6.0
  sensors: ^2.0.3
  stream_transform: ^2.0.0
  wakelock: ^0.6.1+2
  audioplayers: ^1.0.1
  provider: ^6.0.3
  vibration: ^1.7.4-nullsafety.0
  firebase_core : ^1.18.0
  firebase_crashlytics: ^2.8.2
  firebase_analytics: ^9.1.10
  # https://pub.dev/packages/flutter_launcher_icons#book-guide
  flutter_launcher_icons: ^0.9.3 # flutter pub run flutter_launcher_icons:main
  url_launcher: ^6.1.3
  package_info: ^2.0.2
  device_info: ^2.0.3
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  collection: ^1.16.0
  intl: ^0.17.0
  xml: ^5.3.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_driver:
#    sdk: flutter
  test: ^1.21.1
  intl_utils: ^2.6.1
  mockito: ^5.2.0
  sync_translation_files:
    path: scripts/sync_translation_files

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/android.png"
  image_path_ios: "assets/ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/data/topics/
    - assets/data/questions/
    - assets/data/
    - assets/activity_icons/
    - assets/
    - google_fonts/Ubuntu-Regular.ttf
    - google_fonts/UFL.txt

flutter_intl:
  enable: true
  default: cs