name: act_draw_explain
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.0+10

environment:
  sdk: ">=2.6.0 <3.0.0"

# `flutter pub outdated` to see what can be upgraded
dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+3
  sprintf: ^4.0.2
  auto_size_text: ^2.1.0
  preferences: ^5.2.0
  sensors: ">=0.4.1+10 <2.0.0"
  stream_transform: ^1.2.0
  wakelock: ^0.1.4+1
  audioplayers: ^0.15.0
  provider: ^4.0.5
  vibration: ^1.2.4
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  # https://pub.dev/packages/flutter_launcher_icons#book-guide
  flutter_launcher_icons: ^0.7.4  # flutter pub run flutter_launcher_icons:main
  url_launcher: ^5.4.5
  package_info: ^0.4.0+17
  device_info: ">=0.4.2+4 <2.0.0"
  fluttertoast: ^4.0.1
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/android.png"
  image_path_ios: "assets/ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/
