import 'dart:ui';

Locale languageCodeOnlyLocaleFromString(String locale) {
  return Locale(locale.split("_")[0]);
}

bool localeLanguageCodeIn(Locale locale, Iterable<Locale> locales) {
  for (final element in locales) {
    if (locale.languageCode == element.languageCode) return true;
  }

  return false;
}

class Language {
  final String name;
  final String nativeName;

  Language(this.name, this.nativeName);
}

final isoLanguages = {
  "ab": Language("Abkhaz", "аҧсуа"),
  "aa": Language("Afar", "Afaraf"),
  "af": Language("Afrikaans", "Afrikaans"),
  "ak": Language("Akan", "Akan"),
  "sq": Language("Albanian", "Shqip"),
  "am": Language("Amharic", "አማርኛ"),
  "ar": Language("Arabic", "العربية"),
  "an": Language("Aragonese", "Aragonés"),
  "hy": Language("Armenian", "Հայերեն"),
  "as": Language("Assamese", "অসমীয়া"),
  "av": Language("Avaric", "авар мацӀ"),
  "ae": Language("Avestan", "avesta"),
  "ay": Language("Aymara", "aymar aru"),
  "az": Language("Azerbaijani", "azərbaycan dili"),
  "bm": Language("Bambara", "bamanankan"),
  "ba": Language("Bashkir", "башҡорт теле"),
  "eu": Language("Basque", "euskara"),
  "be": Language("Belarusian", "Беларуская"),
  "bn": Language("Bengali", "বাংলা"),
  "bh": Language("Bihari", "भोजपुरी"),
  "bi": Language("Bislama", "Bislama"),
  "bs": Language("Bosnian", "bosanski jezik"),
  "br": Language("Breton", "brezhoneg"),
  "bg": Language("Bulgarian", "български език"),
  "my": Language("Burmese", "ဗမာစာ"),
  "ca": Language("Catalan; Valencian", "Català"),
  "ch": Language("Chamorro", "Chamoru"),
  "ce": Language("Chechen", "нохчийн мотт"),
  "ny": Language("Chichewa", "chiCheŵa"),
  "zh": Language("Chinese", "中文"),
  "cv": Language("Chuvash", "чӑваш чӗлхи"),
  "kw": Language("Cornish", "Kernewek"),
  "co": Language("Corsican", "corsu"),
  "cr": Language("Cree", "ᓀᐦᐃᔭᐍᐏᐣ"),
  "hr": Language("Croatian", "hrvatski"),
  "cs": Language("Czech", "čeština"),
  "da": Language("Danish", "dansk"),
  "dv": Language("Maldivian;", "ދިވެހި"),
  "nl": Language("Dutch", "Vlaams"),
  "en": Language("English", "English"),
  "eo": Language("Esperanto", "Esperanto"),
  "et": Language("Estonian", "eesti"),
  "ee": Language("Ewe", "Eʋegbe"),
  "fo": Language("Faroese", "føroyskt"),
  "fj": Language("Fijian", "vosa Vakaviti"),
  "fi": Language("Finnish", "suomi"),
  "fr": Language("French", "français"),
  "ff": Language("Fula", "Fulfulde"),
  "gl": Language("Galician", "Galego"),
  "ka": Language("Georgian", "ქართული"),
  "de": Language("German", "Deutsch"),
  "el": Language("Greek", "Ελληνικά"),
  "gn": Language("Guaraní", "Avañeẽ"),
  "gu": Language("Gujarati", "ગુજરાતી"),
  "ht": Language("Haitian", "Kreyòl ayisyen"),
  "ha": Language("Hausa", "هَوُسَ"),
  "he": Language("Hebrew (modern)", "עברית"),
  "hz": Language("Herero", "Otjiherero"),
  "hi": Language("Hindi", "हिंदी"),
  "ho": Language("Hiri Motu", "Hiri Motu"),
  "hu": Language("Hungarian", "Magyar"),
  "ia": Language("Interlingua", "Interlingua"),
  "id": Language("Indonesian", "Bahasa Indonesia"),
  "ie": Language("Interlingue", "Interlingue"),
  "ga": Language("Irish", "Gaeilge"),
  "ig": Language("Igbo", "Asụsụ Igbo"),
  "ik": Language("Inupiaq", "Iñupiatun"),
  "io": Language("Ido", "Ido"),
  "is": Language("Icelandic", "Íslenska"),
  "it": Language("Italian", "Italiano"),
  "iu": Language("Inuktitut", "ᐃᓄᒃᑎᑐᑦ"),
  "ja": Language("Japanese", "日本語 (にほんご／にっぽんご)"),
  "jv": Language("Javanese", "basa Jawa"),
  "kl": Language("Greenlandic", "kalaallisut"),
  "kn": Language("Kannada", "ಕನ್ನಡ"),
  "kr": Language("Kanuri", "Kanuri"),
  "ks": Language("Kashmiri", "कश्मीरी, كشميري‎"),
  "kk": Language("Kazakh", "Қазақ тілі"),
  "km": Language("Khmer", "ភាសាខ្មែរ"),
  "ki": Language("Gikuyu", "Gĩkũyũ"),
  "rw": Language("Kinyarwanda", "Ikinyarwanda"),
  "ky": Language("Kyrgyz", "кыргыз тили"),
  "kv": Language("Komi", "коми кыв"),
  "kg": Language("Kongo", "KiKongo"),
  "ko": Language("Korean", "한국어"),
  "ku": Language("Kurdish", " كوردی‎"),
  "kj": Language("Kwanyama", "Kuanyama"),
  "la": Language("Latin", "latine"),
  "lb": Language("Luxembourgish", "Lëtzebuergesch"),
  "lg": Language("Luganda", "Luganda"),
  "li": Language("Limburgish", "Limburgs"),
  "ln": Language("Lingala", "Lingála"),
  "lo": Language("Lao", "ພາສາລາວ"),
  "lt": Language("Lithuanian", "lietuvių kalba"),
  "lu": Language("Luba-Katanga", "Luba-Katanga"),
  "lv": Language("Latvian", "latviešu valoda"),
  "gv": Language("Manx", "Gaelg"),
  "mk": Language("Macedonian", "македонски јазик"),
  "mg": Language("Malagasy", "Malagasy fiteny"),
  "ms": Language("Malay", "بهاس ملايو‎"),
  "ml": Language("Malayalam", "മലയാളം"),
  "mt": Language("Maltese", "Malti"),
  "mi": Language("Māori", "te reo Māori"),
  "mr": Language("Marathi (Marāṭhī)", "मराठी"),
  "mh": Language("Marshallese", "Kajin M̧ajeļ"),
  "mn": Language("Mongolian", "монгол"),
  "na": Language("Nauru", "Ekakairũ Naoero"),
  "nv": Language("Navajo", "Dinékʼehǰí"),
  "nb": Language("Norwegian Bokmål", "Norsk bokmål"),
  "nd": Language("North Ndebele", "isiNdebele"),
  "ne": Language("Nepali", "नेपाली"),
  "ng": Language("Ndonga", "Owambo"),
  "nn": Language("Norwegian Nynorsk", "Norsk nynorsk"),
  "no": Language("Norwegian", "Norsk"),
  "ii": Language("Nuosu", "ꆈꌠ꒿ Nuosuhxop"),
  "nr": Language("South Ndebele", "isiNdebele"),
  "oc": Language("Occitan", "Occitan"),
  "oj": Language("Ojibwe", "ᐊᓂᔑᓈᐯᒧᐎᓐ"),
  "cu": Language("Old Church Slavonic", "ѩзыкъ словѣньскъ"),
  "om": Language("Oromo", "Afaan Oromoo"),
  "or": Language("Oriya", "ଓଡ଼ିଆ"),
  "os": Language("Ossetian", "ирон æвзаг"),
  "pa": Language("Panjabi", "پنجابی‎"),
  "pi": Language("Pāli", "पाऴि"),
  "fa": Language("Persian", "فارسی"),
  "pl": Language("Polish", "polski"),
  "ps": Language("Pashto,", "پښتو"),
  "pt": Language("Portuguese", "Português"),
  "qu": Language("Quechua", "Runa Simi"),
  "rm": Language("Romansh", "rumantsch grischun"),
  "rn": Language("Kirundi", "kiRundi"),
  "ro": Language("Romanian", "română"),
  "ru": Language("Russian", "русский язык"),
  "sa": Language("Sanskrit (Saṁskṛta)", "संस्कृतम्"),
  "sc": Language("Sardinian", "sardu"),
  "sd": Language("Sindhi", "سنڌي، سندھی‎"),
  "se": Language("Northern Sami", "Davvisámegiella"),
  "sm": Language("Samoan", "gagana faa Samoa"),
  "sg": Language("Sango", "yângâ tî sängö"),
  "sr": Language("Serbian", "српски језик"),
  "gd": Language("Scottish Gaelic", "Gàidhlig"),
  "sn": Language("Shona", "chiShona"),
  "si": Language("Sinhala", "සිංහල"),
  "sk": Language("Slovak", "slovenčina"),
  "sl": Language("Slovene", "slovenščina"),
  "so": Language("Somali", "af Soomaali"),
  "st": Language("Southern Sotho", "Sesotho"),
  "es": Language("Spanish", "español"),
  "su": Language("Sundanese", "Basa Sunda"),
  "sw": Language("Swahili", "Kiswahili"),
  "ss": Language("Swati", "SiSwati"),
  "sv": Language("Swedish", "svenska"),
  "ta": Language("Tamil", "தமிழ்"),
  "te": Language("Telugu", "తెలుగు"),
  "tg": Language("Tajik", "تاجیکی‎"),
  "th": Language("Thai", "ไทย"),
  "ti": Language("Tigrinya", "ትግርኛ"),
  "bo": Language("Tibetan", "བོད་ཡིག"),
  "tk": Language("Turkmen", "Түркмен"),
  "tl": Language("Tagalog", "Wikang Tagalog"),
  "tn": Language("Tswana", "Setswana"),
  "to": Language("Tonga", "faka Tonga"),
  "tr": Language("Turkish", "Türkçe"),
  "ts": Language("Tsonga", "Xitsonga"),
  "tt": Language("Tatar", "татарча, tatarça, تاتارچا‎"),
  "tw": Language("Twi", "Twi"),
  "ty": Language("Tahitian", "Reo Tahiti"),
  "ug": Language("Uighur", "Uyƣurqə, ئۇيغۇرچە‎"),
  "uk": Language("Ukrainian", "українська"),
  "ur": Language("Urdu", "اردو"),
  "uz": Language("Uzbek", "zbek, Ўзбек, أۇزبېك‎"),
  "ve": Language("Venda", "Tshivenḓa"),
  "vi": Language("Vietnamese", "Tiếng Việt"),
  "vo": Language("Volapük", "Volapük"),
  "wa": Language("Walloon", "Walon"),
  "cy": Language("Welsh", "Cymraeg"),
  "wo": Language("Wolof", "Wollof"),
  "fy": Language("Western Frisian", "Frysk"),
  "xh": Language("Xhosa", "isiXhosa"),
  "yi": Language("Yiddish", "ייִדיש"),
  "yo": Language("Yoruba", "Yorùbá"),
  "za": Language("Zhuang", "Saɯ cueŋƅ")
};
